experiment_name = ""                         # A unique ID used to distinguish experiments.
splitting = "full"                           # Dataset solitting used in this experiment.
save_root_dir = "."                          # The root directory for storing data and results.
hf_token = "none"                            # Used to speed up data download from HuggingFace. Setting it to "none" disables it.
hf_repo_id = "SWE-CI/SWE-CI"                 # The ID of the HuggingFace repository for the dataset.
agent_name = "iflow"                         # CLI Agent for running the experiment. Choose form ["iflow"].
api_key = ""                                 # Secret key for authenticating requests to LLM APIs.
base_url = ""                                # The base URL of the API endpoint for LLM services.
model_name = ""                              # The specific name or ID of the LLM to be invoked.

[agent]
node_version = ""                            # The version of NODE required to install the CLI Agent.
npm_pkg = ""                                 # NPM package name of CLI Agent.
npm_bin = ""                                 # The name of the executable command provided by the NPM package.

[docker]
storage_disk = ""                            # The disk where Docker storage resides. 
cpus = ""                                    # Maximum number of cores that a container can use.
read_bps = "128mb"                           # Maximum number of bytes read per second by the container.
write_bps = "128mb"                          # Maximum number of bytes write per second by the container.
memory = "8192mb"                            # Hard limit for container memory, exceeding this limit will trigger the OOM Killer.
memory_reservation = "4096mb"                # Soft limit for container memory.

[iflow]
auth_type = "openai-compatible"              # Authentication method for using iFlow services. Choose form ["iflow", "openai-compatible"].

[pytest]
timeout = 3600                               # The maximum runtime of pytest (second), exceeding this time will trigger an error.

[init]
max_workers = 16                             # Maximum concurrency of initialization tasks.

[evolve]
max_epoch = 20                               # Maximum number of iterations in code evolution.
max_workers = 16                             # Maximum concurrency of running code evolution tasks.

[evolve.architect]
timeout = 3600                               # Maximum runtime of the architect agent (second).
max_try = 10                                 # The maximum number of attempts for the Architect Agent.

[evolve.programmer]
timeout = 3600                               # Maximum runtime of the programmer agent (second).
max_try = 10                                 # The maximum number of attempts for the programmer agent.